import Grid from "@mui/material/Grid2";
import CardGradRojo, { CardBodyIncon2 } from "./CardGradientRojo.tsx";

type Props = {};

export default function CardGridInconvenientes({}: Props) {
  return (
    <Grid
      container
      direction="row"
      sx={{
        justifyContent: "space-evenly",
        alignItems: "flex-start",
      }}
      spacing={4}
    >
      <Grid>
        <CardGradRojo>
          <CardBodyIncon2
            titleNombre="Jose Luis"
            titleApellido="Cuello"
            textCuil="20xxxxx"
            imagen="https://images.pexels.com/photos/20787/pexels-photo.jpg?auto=compress&cs=tinysrgb&h=350"
            textCelular="3522222"
            textCuitEmpresa="30xxxxxx"
            textPatenteCamion="AB123CD"
            textPatenteSemi1="ABC123"
            textPatenteSemi2="NULL"
          />
        </CardGradRojo>
      </Grid>
      <Grid>
        <CardGradRojo>
          <CardBodyIncon2
            titleNombre="Jose Luis"
            titleApellido="Cuello"
            textCuil="20xxxxx"
            imagen="https://images.pexels.com/photos/20787/pexels-photo.jpg?auto=compress&cs=tinysrgb&h=350"
            textCelular="3522222"
            textCuitEmpresa="30xxxxxx"
            textPatenteCamion="AB123CD"
            textPatenteSemi1="ABC123"
            textPatenteSemi2="NULL"
          />
        </CardGradRojo>
      </Grid>
      <Grid>
        <CardGradRojo>
          <CardBodyIncon2
            titleNombre="Jose Luis"
            titleApellido="Cuello"
            textCuil="20xxxxx"
            imagen="https://images.pexels.com/photos/20787/pexels-photo.jpg?auto=compress&cs=tinysrgb&h=350"
            textCelular="3522222"
            textCuitEmpresa="30xxxxxx"
            textPatenteCamion="AB123CD"
            textPatenteSemi1="ABC123"
            textPatenteSemi2="NULL"
          />
        </CardGradRojo>
      </Grid>
      <Grid>
        <CardGradRojo>
          <CardBodyIncon2
            titleNombre="Jose Luis"
            titleApellido="Cuello"
            textCuil="20xxxxx"
            imagen="https://images.pexels.com/photos/20787/pexels-photo.jpg?auto=compress&cs=tinysrgb&h=350"
            textCelular="3522222"
            textCuitEmpresa="30xxxxxx"
            textPatenteCamion="AB123CD"
            textPatenteSemi1="ABC123"
            textPatenteSemi2="NULL"
          />
        </CardGradRojo>
      </Grid>
      <Grid>
        <CardGradRojo>
          <CardBodyIncon2
            titleNombre="Jose Luis"
            titleApellido="Cuello"
            textCuil="20xxxxx"
            imagen="https://images.pexels.com/photos/20787/pexels-photo.jpg?auto=compress&cs=tinysrgb&h=350"
            textCelular="3522222"
            textCuitEmpresa="30xxxxxx"
            textPatenteCamion="AB123CD"
            textPatenteSemi1="ABC123"
            textPatenteSemi2="NULL"
          />
        </CardGradRojo>
      </Grid>
      <Grid>
        <CardGradRojo>
          <CardBodyIncon2
            titleNombre="Jose Luis"
            titleApellido="Cuello"
            textCuil="20xxxxx"
            imagen="https://images.pexels.com/photos/20787/pexels-photo.jpg?auto=compress&cs=tinysrgb&h=350"
            textCelular="3522222"
            textCuitEmpresa="30xxxxxx"
            textPatenteCamion="AB123CD"
            textPatenteSemi1="ABC123"
            textPatenteSemi2="NULL"
          />
        </CardGradRojo>
      </Grid>
      <Grid>
        <CardGradRojo>
          <CardBodyIncon2
            titleNombre="Jose Luis"
            titleApellido="Cuello"
            textCuil="20xxxxx"
            imagen="https://images.pexels.com/photos/20787/pexels-photo.jpg?auto=compress&cs=tinysrgb&h=350"
            textCelular="3522222"
            textCuitEmpresa="30xxxxxx"
            textPatenteCamion="AB123CD"
            textPatenteSemi1="ABC123"
            textPatenteSemi2="NULL"
          />
        </CardGradRojo>
      </Grid>
      <Grid>
        <CardGradRojo>
          <CardBodyIncon2
            titleNombre="Jose Luis"
            titleApellido="Cuello"
            textCuil="20xxxxx"
            imagen="https://images.pexels.com/photos/20787/pexels-photo.jpg?auto=compress&cs=tinysrgb&h=350"
            textCelular="3522222"
            textCuitEmpresa="30xxxxxx"
            textPatenteCamion="AB123CD"
            textPatenteSemi1="ABC123"
            textPatenteSemi2="NULL"
          />
        </CardGradRojo>
      </Grid>
      <Grid>
        <CardGradRojo>
          <CardBodyIncon2
            titleNombre="Jose Luis"
            titleApellido="Cuello"
            textCuil="20xxxxx"
            imagen="https://images.pexels.com/photos/20787/pexels-photo.jpg?auto=compress&cs=tinysrgb&h=350"
            textCelular="3522222"
            textCuitEmpresa="30xxxxxx"
            textPatenteCamion="AB123CD"
            textPatenteSemi1="ABC123"
            textPatenteSemi2="NULL"
          />
        </CardGradRojo>
      </Grid>
      <Grid>
        <CardGradRojo>
          <CardBodyIncon2
            titleNombre="Jose Luis"
            titleApellido="Cuello"
            textCuil="20xxxxx"
            imagen="https://images.pexels.com/photos/20787/pexels-photo.jpg?auto=compress&cs=tinysrgb&h=350"
            textCelular="3522222"
            textCuitEmpresa="30xxxxxx"
            textPatenteCamion="AB123CD"
            textPatenteSemi1="ABC123"
            textPatenteSemi2="NULL"
          />
        </CardGradRojo>
      </Grid>
      <Grid>
        <CardGradRojo>
          <CardBodyIncon2
            titleNombre="Jose Luis"
            titleApellido="Cuello"
            textCuil="20xxxxx"
            imagen="https://images.pexels.com/photos/20787/pexels-photo.jpg?auto=compress&cs=tinysrgb&h=350"
            textCelular="3522222"
            textCuitEmpresa="30xxxxxx"
            textPatenteCamion="AB123CD"
            textPatenteSemi1="ABC123"
            textPatenteSemi2="NULL"
          />
        </CardGradRojo>
      </Grid>
      <Grid>
        <CardGradRojo>
          <CardBodyIncon2
            titleNombre="Jose Luis"
            titleApellido="Cuello"
            textCuil="20xxxxx"
            imagen="https://images.pexels.com/photos/20787/pexels-photo.jpg?auto=compress&cs=tinysrgb&h=350"
            textCelular="3522222"
            textCuitEmpresa="30xxxxxx"
            textPatenteCamion="AB123CD"
            textPatenteSemi1="ABC123"
            textPatenteSemi2="NULL"
          />
        </CardGradRojo>
      </Grid>
      <Grid>
        <CardGradRojo>
          <CardBodyIncon2
            titleNombre="Jose Luis"
            titleApellido="Cuello"
            textCuil="20xxxxx"
            imagen="https://images.pexels.com/photos/20787/pexels-photo.jpg?auto=compress&cs=tinysrgb&h=350"
            textCelular="3522222"
            textCuitEmpresa="30xxxxxx"
            textPatenteCamion="AB123CD"
            textPatenteSemi1="ABC123"
            textPatenteSemi2="NULL"
          />
        </CardGradRojo>
      </Grid>
      <Grid>
        <CardGradRojo>
          <CardBodyIncon2
            titleNombre="Jose Luis"
            titleApellido="Cuello"
            textCuil="20xxxxx"
            imagen="https://images.pexels.com/photos/20787/pexels-photo.jpg?auto=compress&cs=tinysrgb&h=350"
            textCelular="3522222"
            textCuitEmpresa="30xxxxxx"
            textPatenteCamion="AB123CD"
            textPatenteSemi1="ABC123"
            textPatenteSemi2="NULL"
          />
        </CardGradRojo>
      </Grid>
      <Grid>
        <CardGradRojo>
          <CardBodyIncon2
            titleNombre="Jose Luis"
            titleApellido="Cuello"
            textCuil="20xxxxx"
            imagen="https://images.pexels.com/photos/20787/pexels-photo.jpg?auto=compress&cs=tinysrgb&h=350"
            textCelular="3522222"
            textCuitEmpresa="30xxxxxx"
            textPatenteCamion="AB123CD"
            textPatenteSemi1="ABC123"
            textPatenteSemi2="NULL"
          />
        </CardGradRojo>
      </Grid>
      <Grid>
        <CardGradRojo>
          <CardBodyIncon2
            titleNombre="Jose Luis"
            titleApellido="Cuello"
            textCuil="20xxxxx"
            imagen="https://images.pexels.com/photos/20787/pexels-photo.jpg?auto=compress&cs=tinysrgb&h=350"
            textCelular="3522222"
            textCuitEmpresa="30xxxxxx"
            textPatenteCamion="AB123CD"
            textPatenteSemi1="ABC123"
            textPatenteSemi2="NULL"
          />
        </CardGradRojo>
      </Grid>
      <Grid>
        <CardGradRojo>
          <CardBodyIncon2
            titleNombre="Jose Luis"
            titleApellido="Cuello"
            textCuil="20xxxxx"
            imagen="https://images.pexels.com/photos/20787/pexels-photo.jpg?auto=compress&cs=tinysrgb&h=350"
            textCelular="3522222"
            textCuitEmpresa="30xxxxxx"
            textPatenteCamion="AB123CD"
            textPatenteSemi1="ABC123"
            textPatenteSemi2="NULL"
          />
        </CardGradRojo>
      </Grid>
      <Grid>
        <CardGradRojo>
          <CardBodyIncon2
            titleNombre="Jose Luis"
            titleApellido="Cuello"
            textCuil="20xxxxx"
            imagen="https://images.pexels.com/photos/20787/pexels-photo.jpg?auto=compress&cs=tinysrgb&h=350"
            textCelular="3522222"
            textCuitEmpresa="30xxxxxx"
            textPatenteCamion="AB123CD"
            textPatenteSemi1="ABC123"
            textPatenteSemi2="NULL"
          />
        </CardGradRojo>
      </Grid>

      <Grid>
        <CardGradRojo>
          <CardBodyIncon2
            titleNombre="Jose Luis"
            titleApellido="Cuello"
            textCuil="20xxxxx"
            imagen="https://images.pexels.com/photos/20787/pexels-photo.jpg?auto=compress&cs=tinysrgb&h=350"
            textCelular="3522222"
            textCuitEmpresa="30xxxxxx"
            textPatenteCamion="AB123CD"
            textPatenteSemi1="ABC123"
            textPatenteSemi2="NULL"
          />
        </CardGradRojo>
      </Grid>
      <Grid>
        <CardGradRojo>
          <CardBodyIncon2
            titleNombre="Jose Luis"
            titleApellido="Cuello"
            textCuil="20xxxxx"
            imagen="https://images.pexels.com/photos/20787/pexels-photo.jpg?auto=compress&cs=tinysrgb&h=350"
            textCelular="3522222"
            textCuitEmpresa="30xxxxxx"
            textPatenteCamion="AB123CD"
            textPatenteSemi1="ABC123"
            textPatenteSemi2="NULL"
          />
        </CardGradRojo>
      </Grid>
      <Grid>
        <CardGradRojo>
          <CardBodyIncon2
            titleNombre="Jose Luis"
            titleApellido="Cuello"
            textCuil="20xxxxx"
            imagen="https://images.pexels.com/photos/20787/pexels-photo.jpg?auto=compress&cs=tinysrgb&h=350"
            textCelular="3522222"
            textCuitEmpresa="30xxxxxx"
            textPatenteCamion="AB123CD"
            textPatenteSemi1="ABC123"
            textPatenteSemi2="NULL"
          />
        </CardGradRojo>
      </Grid>
    </Grid>
  );
}
