name: Build and Push Docker Image to GHCR

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
# Se ejecuta cuando se cierra un pr en la rama main, solo si se ha fusionado
  build-and-push:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}/frontend_service:latest
          build-args: |
            VITE_BACKEND_URL=${{ secrets.VITE_BACKEND_URL }}
            VITE_AUTH_URL=${{ secrets.VITE_AUTH_URL }}
            VITE_DASHBOARD_URL=${{ secrets.VITE_DASHBOARD_URL }}
            VITE_VITE_STAGE=${{ secrets.VITE_STAGE }}
            
      - name: Log out from GitHub Container Registry
        run: docker logout ghcr.io
